IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Images')
BEGIN
    CREATE TABLE Images (
		Id UNIQUEIDENTIFIER NOT NULL,
		Location VARCHAR(255) NOT NULL,
		CONSTRAINT PK_Images PRIMARY KEY (Id)
    );
END