IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Maps')
BEGIN
    CREATE TABLE Maps (
		Id UNIQUEIDENTIFIER NOT NULL,
		ColumnCnt INT NOT NULL,
		RowCnt INT NOT NULL,
		CONSTRAINT PK_Maps PRIMARY KEY (Id)
    );
END