IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Images') AND COL_LENGTH('Images', 'UploadedDate') IS NOT NULL AND COL_LENGTH('Images', 'Status') IS NOT NULL
BEGIN
    ALTER TABLE Images DROP CONSTRAINT FK_Images_Status_Statuses_Id;
	ALTER TABLE Images DROP COLUMN Status, UploadedDate;
END