IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ImageTags') AND COL_LENGTH('ImageTags', 'Tag') IS NOT NULL
BEGIN
	ALTER TABLE ImageTags
		DROP CONSTRAINT PK_ImageTags;
    ALTER TABLE ImageTags
		ALTER COLUMN [Tag] VARCHAR(16) NOT NULL;
	ALTER TABLE ImageTags
		ADD CONSTRAINT PK_ImageTags PRIMARY KEY (ImageId, Tag);
END