IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CompoundImages')
BEGIN
    CREATE TABLE CompoundImages (
		Id UNIQUEIDENTIFIER NOT NULL,
		MapId UNIQUEIDENTIFIER NOT NULL,
		CONSTRAINT PK_CompoundImages PRIMARY KEY (Id),
		CONSTRAINT FK_CompoundImages_MapId_Maps_Id FOREIGN KEY (MapId) REFERENCES Maps(Id)
    );
END