IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ImageTags')
BEGIN
    CREATE TABLE ImageTags (
		ImageId UNIQUEIDENTIFIER NOT NULL,
		Tag VARCHAR(16) NOT NULL,
		Confidence FLOAT NOT NULL,
		MapId UNIQUEIDENTIFIER NULL,
		CONSTRAINT PK_ImageTags PRIMARY KEY (ImageId, Tag),
		CONSTRAINT FK_ImageTags_ImageId_Images_Id FOREIGN KEY (ImageId) REFERENCES Images(Id),
		CONSTRAINT FK_ImageTags_MapId_Maps_Id FOREIGN KEY (MapId) REFERENCES Maps(Id)
    );
END