IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Images') AND COL_LENGTH('Images', 'UploadedDate') IS NULL AND COL_LENGTH('Images', 'Status') IS NULL
BEGIN
    ALTER TABLE Images
		ADD UploadedDate DATETIME NOT NULL,
			Status TINYINT NOT NULL,
			CONSTRAINT FK_Images_Status_Statuses_Id FOREIGN KEY (Status) REFERENCES Statuses(Id);
END